[tool.isort]
profile = "black"
line_length = 119
src_paths = ['src']


[tool.blue]
line-length = 119


[tool.mypy]
check_untyped_defs = true
strict = true
plugins = ["pydantic.mypy"]


[tool.pytest.ini_options]
env = [
    "SQLALCHEMY_DATABASE_URL=postgresql+asyncpg://nik:qwe123@localhost/anserv_test",
]