"""Initial

Revision ID: 234d702c511c
Revises: 
Create Date: 2023-03-15 15:38:46.203469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234d702c511c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
