"""empty message

Revision ID: 93b6b3df8f73
Revises: 7e004ac152bc
Create Date: 2023-03-16 13:33:14.711449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93b6b3df8f73'
down_revision = '7e004ac152bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('teams', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'teams')
    # ### end Alembic commands ###
