[tool.isort]
profile = "black"
line_length = 119
src_paths = ['.']


[tool.blue]
line-length = 119


[tool.mypy]
check_untyped_defs = true
strict = true
plugins = ["pydantic.mypy"]


[tool.pytest.ini_options]
env = [
    "POSTGRES_DB=anserv_test",
    "SQLALCHEMY_USE_NULLPOOL=true"
]